using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;
using Bunq.Sdk.Security;
using Lakerfield.BunqSdk.Model;

namespace Lakerfield.BunqSdk.Context
{
  public class InstallationContext
  {
    public string Token { get; private set; }
    public RSA KeyPairClient { get; private set; }
    public RSA PublicKeyServer { get; private set; }

    internal InstallationContext(Token sessionToken,  ServerPublicKey serverPublicKey, RSA keyPairClient) :
      this(sessionToken.Value, keyPairClient,
        SecurityUtils.CreatePublicKeyFromPublicKeyFormattedString(serverPublicKey.Value))
    {
    }

    /// <param name="token">Installation token returned as a response to the POST /installation</param>
    /// <param name="keyPairClient">Client key pair generated by SDK (Private + Public)</param>
    /// <param name="publicKeyServer">Server public key returned as a response to the POST /installation</param>
    public InstallationContext(string token, RSA keyPairClient, RSA publicKeyServer)
    {
      Token = token;
      KeyPairClient = keyPairClient;
      PublicKeyServer = publicKeyServer;
    }



  }
}
